name: MemoryStone
main: za.dats.bukkit.memorystone.MemoryStonePlugin
version: 1.0.0
website: http://www.dats.co.za
author: CmdrDats
description: >
             Build Memory Stones out of Stone and Obsidian and a Sign to name it
             Tap a Memory Stone with your compass to memorize its location
             Right click with a compass to select a memorized stone to teleport to
permissions:
  memorystone.*:
    discription: gives access to all normal MemoryStone permissions
    children:
      memorystone.build: true
      memorystone.break: true
      memorystone.use: true
      memorystone.useonothers: true
  memorystone.build:
    description: allows user to build Memory Stones
    default: true
  memorystone.break:
    description: allows user to break Memory Stones
    default: true
  memorystone.use:
    description: allows user to teleport
    default: true
  memorystone.usefree:
    description: allows user to teleport without costing charges (if applicable)
    default: false
  memorystone.useonothers:
    description: allows user to teleport others
    default: true
             
